-- Ejecutar una vez en Supabase SQL Editor.
-- Ajusta el tipo de dui si en tu instalación no es numeric.

alter table public."Usuario"
  add column if not exists avatar text;

alter table public."Usuario"
  add column if not exists intereses text[] default '{}';

alter table public."Usuario"
  add column if not exists biografia text;

alter table public."Usuario"
  add column if not exists rango_inversion text;

alter table public."Usuario"
  add column if not exists nivel_riesgo text;

alter table public."Usuario"
  add column if not exists disponibilidad_contacto text;

alter table public.proyecto
  add column if not exists imagen_url text;

alter table public.proyecto
  add column if not exists contrato_url text;

alter table public.proyecto
  add column if not exists ganancia_esperada numeric
    check (ganancia_esperada is null or ganancia_esperada > 0);

alter table public.proyecto
  add column if not exists plazo_retorno_meses integer
    check (plazo_retorno_meses is null or plazo_retorno_meses > 0);

alter table public.inversion
  add column if not exists id_inversionista numeric;

alter table public.pago
  add column if not exists id_inversion bigint;

do $$
begin
  alter table public.pago
    add constraint pago_id_inversion_fkey
    foreign key (id_inversion) references public.inversion(id_inversion);
exception
  when duplicate_object then null;
end $$;

create sequence if not exists public.proyecto_id_proyecto_seq;

alter sequence public.proyecto_id_proyecto_seq owned by public.proyecto.id_proyecto;

alter table public.proyecto
  alter column id_proyecto set default nextval('public.proyecto_id_proyecto_seq');

select setval(
  'public.proyecto_id_proyecto_seq',
  greatest(coalesce((select max(id_proyecto) from public.proyecto), 0), 1)::bigint,
  true
);

alter table public.inversion
  drop constraint if exists inversion_id_inversionista_fkey;

alter table public.pago
  drop constraint if exists "PAGO_ID_inversionista_fkey";

do $$
begin
  alter table public.inversion
    add constraint inversion_id_inversionista_fkey
    foreign key (id_inversionista) references public."Usuario"(dui);
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter table public.pago
    add constraint pago_id_inversionista_fkey
    foreign key (id_inversionista) references public."Usuario"(dui);
exception
  when duplicate_object then null;
end $$;

insert into public.categoria (id_categoria, nombre, descripcion)
values
  ('tecnologia', 'Technology', 'Technology and digital products'),
  ('agricultura', 'Agriculture', 'Agriculture and food production'),
  ('comercio', 'Commerce', 'Retail and commerce'),
  ('servicios', 'Services', 'Professional and community services')
on conflict (id_categoria) do nothing;

create table if not exists public.preferencias_usuario (
  dui numeric primary key,
  alertas_transacciones boolean not null default true,
  sugerencias_marketing boolean not null default false
);

do $$
begin
  alter table public.preferencias_usuario
    add constraint preferencias_usuario_dui_fkey
    foreign key (dui) references public."Usuario"(dui) on delete cascade;
exception
  when duplicate_object then null;
end $$;

create index if not exists inversion_inversionista_idx
  on public.inversion (id_inversionista);

create index if not exists inversion_proyecto_idx
  on public.inversion (id_proyecto);

create index if not exists pago_inversionista_idx
  on public.pago (id_inversionista);

create index if not exists pago_inversion_idx
  on public.pago (id_inversion);

-- Tablas auxiliares usadas por la aplicación.
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id numeric not null,
  title text not null,
  body text,
  link text,
  created_at timestamptz not null default now(),
  is_read boolean not null default false
);

create table if not exists public.support_requests (
  id bigint generated by default as identity primary key,
  dui numeric not null references public."Usuario"(dui) on delete cascade,
  subject text not null,
  message text not null,
  status text not null default 'open',
  created_at timestamptz not null default now()
);

create index if not exists support_requests_user_created_idx
  on public.support_requests (dui, created_at desc);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);

create table if not exists public.chat_conversations (
  id bigint generated by default as identity primary key,
  id_proyecto integer references public.proyecto(id_proyecto) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.chat_conversations
  add column if not exists id_proyecto integer references public.proyecto(id_proyecto) on delete set null;

create unique index if not exists chat_conversations_project_idx
  on public.chat_conversations (id_proyecto)
  where id_proyecto is not null;

create table if not exists public.chat_participants (
  conversation_id bigint not null references public.chat_conversations(id) on delete cascade,
  dui numeric not null,
  primary key (conversation_id, dui)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.chat_conversations(id) on delete cascade,
  sender_dui numeric not null,
  body text not null check (length(trim(body)) > 0),
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists chat_messages_conversation_created_idx
  on public.chat_messages (conversation_id, created_at);

-- Realtime permite que la bandeja de notificaciones se actualice sin recargar.
alter table public.notifications replica identity full;
alter table public.chat_messages replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception
  when duplicate_object then null;
end $$;

insert into storage.buckets (id, name, public)
values ('project-images', 'project-images', true)
on conflict (id) do update set public = excluded.public;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'project_images_public_read') then
    create policy project_images_public_read
      on storage.objects for select
      using (bucket_id = 'project-images');
  end if;
end $$;

insert into storage.buckets (id, name, public)
values ('profile-images', 'profile-images', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "Public can manage project documents" on storage.objects;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'project_images_public_upload') then
    create policy project_images_public_upload
      on storage.objects for insert
      with check (bucket_id = 'project-images');
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public can upload profile images') then
    create policy "Public can upload profile images"
      on storage.objects for insert
      to public
      with check (bucket_id = 'profile-images');
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public can update profile images') then
    create policy "Public can update profile images"
      on storage.objects for update
      to public
      using (bucket_id = 'profile-images')
      with check (bucket_id = 'profile-images');
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public can read profile images') then
    create policy "Public can read profile images"
      on storage.objects for select
      to public
      using (bucket_id = 'profile-images');
  end if;
end $$;

-- A confirmed payment produces an immutable snapshot of the investment terms.
create table if not exists public.investment_contracts (
  id_inversion bigint primary key references public.inversion(id_inversion) on delete restrict,
  id_proyecto integer not null references public.proyecto(id_proyecto) on delete restrict,
  id_inversionista numeric not null references public."Usuario"(dui) on delete restrict,
  id_emprendedor numeric not null references public."Usuario"(dui) on delete restrict,
  inversionista_nombre text not null,
  emprendedor_nombre text not null,
  proyecto_nombre text not null,
  monto numeric not null check (monto > 0),
  participacion numeric not null check (participacion >= 0),
  ganancia_esperada_proyecto numeric,
  ganancia_estimada_inversionista numeric,
  plazo_retorno_meses integer,
  fecha_pago date not null,
  fecha_inicio date,
  fecha_limite_retorno date,
  created_at timestamptz not null default now()
);

alter table public.investment_contracts
  add column if not exists ganancia_esperada_proyecto numeric;

alter table public.investment_contracts
  add column if not exists ganancia_estimada_inversionista numeric;

alter table public.investment_contracts
  add column if not exists plazo_retorno_meses integer;

alter table public.investment_contracts replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.investment_contracts;
exception
  when duplicate_object then null;
end $$;

create index if not exists investment_contracts_emprendedor_idx
  on public.investment_contracts (id_emprendedor, created_at desc);

create or replace function public.create_investment_contract_for_confirmed_payment()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if lower(trim(coalesce(new.estado, ''))) not in (
    'paid', 'completed', 'confirmed', 'confirmado', 'pagado', 'completado'
  ) then
    return new;
  end if;

  if new.id_inversion is null then
    return new;
  end if;

  insert into public.investment_contracts (
    id_inversion,
    id_proyecto,
    id_inversionista,
    id_emprendedor,
    inversionista_nombre,
    emprendedor_nombre,
    proyecto_nombre,
    monto,
    participacion,
    ganancia_esperada_proyecto,
    ganancia_estimada_inversionista,
    plazo_retorno_meses,
    fecha_pago,
    fecha_inicio,
    fecha_limite_retorno
  )
  select
    i.id_inversion,
    p.id_proyecto,
    i.id_inversionista,
    p.dui,
    coalesce(nullif(trim(concat_ws(' ', inversionista.nombre, inversionista.apellidos)), ''), 'Inversionista'),
    coalesce(nullif(trim(concat_ws(' ', emprendedor.nombre, emprendedor.apellidos)), ''), 'Emprendedor'),
    p.nombre,
    i.monto,
    coalesce(i.participacion, 0),
    p.ganancia_esperada,
    p.ganancia_esperada * coalesce(i.participacion, 0) / 100,
    p.plazo_retorno_meses,
    coalesce(new.fecha, current_date),
    p.fecha_inicio,
    case
      when p.plazo_retorno_meses > 0
        then (coalesce(new.fecha, current_date) + p.plazo_retorno_meses * interval '1 month')::date
      else p.fecha_fin
    end
  from public.inversion i
  join public.proyecto p on p.id_proyecto = i.id_proyecto
  left join public."Usuario" inversionista on inversionista.dui = i.id_inversionista
  left join public."Usuario" emprendedor on emprendedor.dui = p.dui
  where i.id_inversion = new.id_inversion
  on conflict (id_inversion) do nothing;

  if not found and not exists (
    select 1
    from public.investment_contracts c
    where c.id_inversion = new.id_inversion
  ) then
    raise exception 'Could not create investment contract for investment %', new.id_inversion;
  end if;

  return new;
end;
$$;

drop trigger if exists pago_create_investment_contract on public.pago;
create trigger pago_create_investment_contract
after insert or update on public.pago
for each row
execute function public.create_investment_contract_for_confirmed_payment();

insert into public.investment_contracts (
  id_inversion,
  id_proyecto,
  id_inversionista,
  id_emprendedor,
  inversionista_nombre,
  emprendedor_nombre,
  proyecto_nombre,
  monto,
  participacion,
  ganancia_esperada_proyecto,
  ganancia_estimada_inversionista,
  plazo_retorno_meses,
  fecha_pago,
  fecha_inicio,
  fecha_limite_retorno
)
select
  i.id_inversion,
  p.id_proyecto,
  i.id_inversionista,
  p.dui,
  coalesce(nullif(trim(concat_ws(' ', inversionista.nombre, inversionista.apellidos)), ''), 'Inversionista'),
  coalesce(nullif(trim(concat_ws(' ', emprendedor.nombre, emprendedor.apellidos)), ''), 'Emprendedor'),
  p.nombre,
  i.monto,
  coalesce(i.participacion, 0),
  p.ganancia_esperada,
  p.ganancia_esperada * coalesce(i.participacion, 0) / 100,
  p.plazo_retorno_meses,
  coalesce(pg.fecha, current_date),
  p.fecha_inicio,
  case
    when p.plazo_retorno_meses > 0
      then (coalesce(pg.fecha, current_date) + p.plazo_retorno_meses * interval '1 month')::date
    else p.fecha_fin
  end
from public.pago pg
join public.inversion i on i.id_inversion = pg.id_inversion
join public.proyecto p on p.id_proyecto = i.id_proyecto
left join public."Usuario" inversionista on inversionista.dui = i.id_inversionista
left join public."Usuario" emprendedor on emprendedor.dui = p.dui
where lower(trim(coalesce(pg.estado, ''))) in (
  'paid', 'completed', 'confirmed', 'confirmado', 'pagado', 'completado'
)
on conflict (id_inversion) do nothing;