-- Ejecutar una vez en Supabase SQL Editor.
-- Ajusta el tipo de dui si en tu instalación no es numeric.

alter table public."Usuario"
  add column if not exists avatar text;

alter table public."Usuario"
  add column if not exists intereses text[] default '{}';

alter table public."Usuario"
  add column if not exists biografia text;

alter table public."Usuario"
  add column if not exists rango_inversion text;

alter table public."Usuario"
  add column if not exists nivel_riesgo text;

alter table public."Usuario"
  add column if not exists disponibilidad_contacto text;

alter table public.proyecto
  add column if not exists imagen_url text;

alter table public.proyecto
  add column if not exists contrato_url text;

alter table public.inversion
  add column if not exists id_inversionista numeric;

alter table public.pago
  add column if not exists id_inversion bigint;

create table if not exists public.preferencias_usuario (
  dui numeric primary key,
  alertas_transacciones boolean not null default true,
  sugerencias_marketing boolean not null default false
);

create index if not exists inversion_inversionista_idx
  on public.inversion (id_inversionista);

create index if not exists inversion_proyecto_idx
  on public.inversion (id_proyecto);

create index if not exists pago_inversionista_idx
  on public.pago (id_inversionista);

create index if not exists pago_inversion_idx
  on public.pago (id_inversion);

-- Tablas auxiliares usadas por la aplicación.
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id numeric not null,
  title text not null,
  body text,
  link text,
  created_at timestamptz not null default now(),
  is_read boolean not null default false
);

create index if not exists notifications_user_created_idx
  on public.notifications (user_id, created_at desc);

create table if not exists public.chat_conversations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_participants (
  conversation_id bigint not null references public.chat_conversations(id) on delete cascade,
  dui numeric not null,
  primary key (conversation_id, dui)
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.chat_conversations(id) on delete cascade,
  sender_dui numeric not null,
  body text not null check (length(trim(body)) > 0),
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index if not exists chat_messages_conversation_created_idx
  on public.chat_messages (conversation_id, created_at);

-- Realtime permite que la bandeja de notificaciones se actualice sin recargar.
alter table public.notifications replica identity full;
alter table public.chat_messages replica identity full;

do $$
begin
  alter publication supabase_realtime add table public.notifications;
exception
  when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.chat_messages;
exception
  when duplicate_object then null;
end $$;

insert into storage.buckets (id, name, public)
values ('project-images', 'project-images', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('profile-images', 'profile-images', true)
on conflict (id) do update set public = excluded.public;

insert into storage.buckets (id, name, public)
values ('project-documents', 'project-documents', true)
on conflict (id) do update set public = excluded.public;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public can manage project documents') then
    create policy "Public can manage project documents"
      on storage.objects for all
      to public
      using (bucket_id = 'project-documents')
      with check (bucket_id = 'project-documents');
  end if;
end $$;

do $$
begin
  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public can upload profile images') then
    create policy "Public can upload profile images"
      on storage.objects for insert
      to public
      with check (bucket_id = 'profile-images');
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public can update profile images') then
    create policy "Public can update profile images"
      on storage.objects for update
      to public
      using (bucket_id = 'profile-images')
      with check (bucket_id = 'profile-images');
  end if;

  if not exists (select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'Public can read profile images') then
    create policy "Public can read profile images"
      on storage.objects for select
      to public
      using (bucket_id = 'profile-images');
  end if;
end $$;